<h2 class="display-4 text-center">Crawl through websites</h2>

<br />  

<form action="/analyze" method="post" id="start-form">

    <div class="form-group form-floating">
        <label for="domain" class="text-muted" style="padding: 17px 0 0 12px">https://agencyanalytics.com</label>
        <input style="padding: 0 0 0 210px" type="text" name="url_path" value="/" id="domain" class="form-control" placeholder="Enter domain" />
        <input type="hidden" name="domain" value="https://agencyanalytics.com" />
        <small class="form-text text-muted">Provide URL path for https://agencyanalytics.com. E.g. /feature/white-label</small>
    </div>
    
    <div class="form-group mt-3">
        <!--  label for="numpages">Number of pages to crawl</label -->
        <input type="text" id="numpages" name="numpages" class="form-control" value="0" />
        <small class="form-text text-muted">Provide number of internal pages to crawl.</small>
    </div>
    
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button id="sbmt-btn" type="submit" class="btn btn-primary me-md-2" >Get Analytics</button>
    </div>

</form>
<script type="text/javascript">

document.getElementById('start-form').onsubmit = function() {
	document.getElementById('sbmt-btn').disabled  = true;
	document.getElementById('sbmt-btn').innerHTML = 'Processing ...';

	return true;
}

</script>