<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Web Crawler v1.0</title>
    <link rel="stylesheet" 
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <?php echo $this->getContent(); ?>
    </div>
    
    <br />
    <br />
    
    <div class="text-center p-4">
        &copy; 2023 WebCrawler prototype by Dan Sazonov.
    </div>
</body>
</html>